- src/App.tsx
- src/components/common/LoginInput.tsx
<br>
<br>
close #2 
<br>
<br>
- <br>
- <br>
<br>
> [Design/#2]로그인 인풋 퍼블리싱

- src/components/common/RectangleButton.tsx
- src/components/common/RoundButton.tsx
RoundButton.tsx, RectangleButton.tsx 생성 
<br>
<br>
close #4 
<br>
<br>
- RoundButton.tsx, RectangleButton.tsx 생성 <br>
- <br>
<br>
> design: 2개 버튼 생성

- src/App.tsx
- src/components/common/LoginInput.tsx
- src/main.tsx
- src/styles/GlobalStyle.ts
<br>
<br>
close #8
<br>
<br>
- <br>
- <br>
<br>
> [Design/#8] 로그인 인풋 styled component 퍼블리싱

- src/components/common/Btn.tsx
- src/components/common/RectangleBtn.tsx
- src/components/common/RectangleButton.tsx
- src/components/common/RoundButton.tsx
styled component로 변환 및 파일 수정
<br>
<br>
close #10
<br>
<br>
- styled component로 변환
-  버튼 이름이 너무 길어서 수정
- font-size 수정
- 필요 없는 field 제거
- <br>
- <br>
<br>
> [Design/#10] styled component로 변환 및 이름 변경

- src/assets/SVG.tsx
- src/components/common/Chatting.tsx
<br>
<br>
close #28 
<br>
<br>
- <br>
- <br>
<br>
> [design/#28] 채팅 컴포넌트

- package.json
- src/components/common/Camera.tsx
- src/router.tsx
- yarn.lock
<br>
<br>
close #32 
<br>
<br>
- <br>
- <br>
<br>
> [design/#32]카메라 컴포넌트 퍼블리싱(중간점검)

- package.json
- src/App.tsx
- src/components/calender/Calender.tsx
- src/components/calender/CalenderStyle.tsx
- src/components/modal/Modal.tsx
- yarn.lock
<br>
캘린더 컴포넌트 생성 및 샘플 이미지 데이터 삽입
<br>
close #25 
<br>
<br>
- <br>
- <br>
<br>
> [design/#25] 달력 컴포넌트 퍼블리싱

- src/components/common/Btn.tsx
- src/components/common/LoginInput.tsx
- src/components/modal/Modal.tsx
- src/pages/LogInPage.tsx
- src/router.tsx
<br>
<br>
close #47
<br>
<br>
- <br>
> [design/#47] 모달 반응형 감정 변경

- src/pages/DiaryPage.tsx
- src/router.tsx
<br>
<br>
close #51
<br>
<br>
- <br>
- <br>
<br>
> [Design/#51]일기 퍼블리싱

- src/components/common/MyMessage.tsx
- src/components/common/OpponentMessage.tsx
<br>
<br>
close #53 
<br>
<br>
- <br>
- <br>
<br>
> [Design/#53]챗박스 반응형

- src/components/common/ChattingResult.tsx
- src/pages/Result.tsx
- src/router.tsx
<br>
<br>
close #59
<br>
<br>
- <br>
- <br>
<br>
> [design/#59] chattingresult 컴포넌트no 반응 result 페이지 no 반응

- src/components/common/LoginInput.tsx
- src/pages/LogInPage.tsx
<br>
<br>
close #63
<br>
<br>
- <br>
- <br>
<br>
> [Design/#63]로그인 인풋 정렬 수정

- package.json
- src/components/modal/CameraModal.tsx
- src/router.tsx
- yarn.lock
<br>
<br>
close #61
<br>
<br>
- <br>
- <br>
<br>
> [Design/#61] camera 모달 추가 (반응형O)

- src/components/common/ChatInfo.tsx
- src/components/common/Chatting.tsx
- src/pages/ChatPage.tsx
- src/stores/toggle.ts
<br>
<br>
close #69
<br>
<br>
- <br>
- <br>
<br>
> [design/#69] chatInfo 컴포넌트 생성 및 chatpage 레이아웃 조정

- package.json
- public/mockServiceWorker.js
- src/api/config.ts
- src/api/login/login.ts
- src/components/common/Btn.tsx
- src/components/common/LoginInput.tsx
- src/hooks/useInput.ts
- src/pages/IntroPage.tsx
- src/pages/LogInPage.tsx
- src/pages/MainPage.tsx
- src/pages/SignupPage.tsx
- yarn.lock
<br>
<br>
close #67
<br>
<br>
- <br>
- <br>
<br>
> [Feat/#67]로그인 axios 연결

- package.json
- src/App.tsx
- src/components/common/Btn.tsx
- src/pages/LogInPage.tsx
- src/utils/cookie.ts
- yarn.lock
<br>
<br>
close #74
<br>
<br>
- <br>
- <br>
<br>
> [feat/#74]로그인 api연결 완

- src/components/common/Btn.tsx
- src/components/common/LoginInput.tsx
- src/pages/SignupPage.tsx
<br>
<br>
close #73 
<br>
<br>
- <br>
- <br>
<br>
> [feat/#73]회원가입 axios 연결

- src/components/common/Chatting.tsx
- src/pages/MainPage.tsx
createChatRoom API 연동
<br>
<br>
close #88
<br>
<br>
- <br>
- <br>
<br>
> [feat/#88] createChatRoom API 연동

- src/pages/LogInPage.tsx
- src/pages/MainPage.tsx
logout API 연동
<br>
<br>
close #93
<br>
<br>
- <br>
- <br>
<br>
> [feat/#93] logout API 연동

- src/pages/ChatPage.tsx
- src/pages/LogInPage.tsx
웹소켓 연결 및 연결 해제. 
<br>
<br>
close #90 
<br>
<br>
- <br>
- <br>
<br>
> [Feat/#90] 웹소켓 연결 및 연결 해제

- package.json
- src/components/modal/CameraModal.tsx
- src/pages/DiaryPage.tsx
- yarn.lock
<br>
사진 촬영 api 연동
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>
> [Feat/#91] 사진 촬영 api 연동

- src/components/common/Btn.tsx
- src/components/common/LoginInput.tsx
- src/pages/IntroPage.tsx
<br>
<br>
close #100
<br>
<br>
- <br>
- <br>
<br>
> [Design/#100] 노란 오류 해결 (Typescript 콘솔 오류)

- src/components/modal/CameraModal.tsx
- src/pages/ChatPage.tsx
- src/pages/DiaryPage.tsx
1. 페이지 이동 및 백그라운드 이미지 안뜨는거 해결
2. 
<br>
<br>
이슈 닫지 않고 추가적으로 브렌치 파서 이용할것
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>
> [feat/#102] 페이지 이동 및 백그라운드 이미지 안뜨는거 해결

- src/components/calender/Calender.tsx
- src/components/calender/CalenderStyle.tsx
- src/pages/BookCover.tsx
<br>
달력 일정 누르면 해당 일기 조회 
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>
> [Feat/#95] 달력 일정 누르면 해당 일기 조회

- src/components/common/AudioRecorder.tsx
- src/components/common/Camera.tsx
- src/components/common/Chatting.tsx
- src/pages/ChatPage.tsx
- src/stores/chat.ts
녹음 기능 구현
<br>
<br>
close #98 
<br>
<br>
- 녹음 기능 구현
- CameraBox 마이크 버튼 오류 수정
<br>
- <br>
<br>
> [feat/#98] 녹음 기능 구현

- src/pages/DiaryPage.tsx
<br>
일기 전체조회 axios 연결 및 디자인 일부 수정
<br>
close #107
<br>
<br>
- <br>
- <br>
<br>
> [feat/#107] 일기 전체조회 axios 연결 및 디자인 일부 수정

- src/components/common/Diary.tsx
- src/pages/BookCover.tsx
- src/pages/ChatPage.tsx
- src/pages/DiaryPage.tsx
<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>
> [feat/#113]북커버 axios 연결

- src/components/common/Btn.tsx
- src/pages/SignupPage.tsx
<br>
아이디 중복확인 api 연동 및 다음 버튼 수정
<br>
close #112 
<br>
<br>
- <br>
- <br>
<br>
> [feat/#112] 아이디 중복확인 api 연동 및 다음 버튼 수정

- package.json
- src/LoadingFallback.tsx
- src/components/modal/ImageModal.tsx
- src/pages/IntroPage.tsx
- src/router.tsx
- yarn.lock
<br>
로딩 페이지 구현 및 이미지 모달 생성
<br>
close #116
<br>
<br>
- <br>
- <br>
<br>
> [design/#116] 로딩 페이지 구현 및 이미지 모달 생성

- src/LoadingFallback.tsx
<br>
로딩 페이지 반응형 생성
<br>
close #119
<br>
<br>
- <br>
- <br>
<br>
> [design/#119] 로딩 페이지 반응형 생성

- src/pages/BookCover.tsx
- src/pages/MainPage.tsx
<br>
<br>
close #131 
<br>
<br>
- <br>
- <br>
<br>
> [feat/#131] 로그아웃시 토큰 삭제

- src/components/common/Diary.tsx
<br>
<br>
close #133 
<br>
<br>
- <br>
- <br>
<br>
> [design/#133] 다이어리 페이지 line-height 재설정

- src/pages/SignupPage.tsx
<br>
회원가입 아이디 중복확인 버튼 기능 수정
<br>
close #130 
<br>
<br>
- <br>
- <br>
<br>
> [feat/#130] 회원가입 아이디 중복확인 버튼 기능 수정

- src/components/common/AudioRecorder.tsx
- src/components/common/CharComponent.tsx
- src/components/gif/Voice.tsx
- src/pages/ChatPage.tsx
- src/stores/chat.ts
기다려줘 문구, 쿼가가 말하는 도중에 끝내기(마이크) 못 누르게, 쿼카 어화둥둥~
<br>
<br>
close #141 
<br>
<br>
- <br>
- <br>
<br>
> [feat/#141] 기다려줘 문구, 쿼가가 말하는 도중에 끝내기(마이크) 못 누르게, 쿼카 어화둥둥~

- src/api/config.ts
<br>
토큰 만료시 로그아웃 처리 기능 구현
<br>
close #152
<br>
<br>
- <br>
- <br>
<br>
> feat: 토큰 만료시 로그아웃 처리 기능 구현

- src/components/common/CharComponent.tsx
- src/components/common/Chatting.tsx
- src/pages/ChatPage.tsx
채팅 해결
한 문장씩
<br>
<br>
close #151 
<br>
<br>
- <br>
- <br>
<br>
> [Feat/#151] 채팅 해결

- src/PrivateRoute.tsx
- src/router.tsx
<br>
토큰 없을 때 로그인 페이지로 이동 처리
<br>
close #154
<br>
<br>
- <br>
- <br>
<br>
> [Feat/#150] 토큰 없을 때 로그인 페이지로 이동 처리

- src/components/common/ChatHistoryInfo.tsx
- src/components/common/Face.tsx
- src/pages/Result.tsx
[refactor/#157] result 페이지 Refactoring
<br>
<br>
close #157 
<br>
<br>
- <br>
- <br>
<br>
> [refactor/#157] result 페이지 Refactoring

- src/router.tsx
<br>
404 페이지로 리디렉팅되지 않는 문제 수정
<br>
<br>
close #160 
<br>
<br>
- <br>
- <br>
<br>
> [Fix/#160] 404 페이지 리디렉팅 수정

- src/components/modal/CameraModal.tsx
<br>
<br>
close #165 
<br>
<br>
- <br>
- <br>
<br>
> [feat/#165] diary 대기시간동안 modal 띄우기
